Updates
Signed-off-by: Adarsh Agrawal <adarsh.agrawal1@ibm.com>

diff --git a/.github/workflows/minio-image.yml b/.github/workflows/minio-image.yml
--- a/.github/workflows/minio-image.yml
+++ b/.github/workflows/minio-image.yml
@@ -45,11 +45,13 @@ jobs:
           exit-code: 1
           ignore-unfixed: true
           output: trivy-result.txt
+        continue-on-error: true
       
       - name: Trivy Scan Result
         run: cat trivy-result.txt
 
       - name: Format Trivy Scan Result
+        if: ${{ steps.trivy.outcome == 'failure' }}
         run: |
           if [ -s trivy-result.txt ]; then
             echo -e "## Vulnerability Scan Results\n<details><summary>Details</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
@@ -57,17 +59,16 @@ jobs:
       
       - name: Comment PR with Trivy scan results
         uses: marocchino/sticky-pull-request-comment@v2
-        if: ${{ hashFiles('formatted-trivy-result.md') != '' }}
+        if: ${{ steps.trivy.outcome == 'failure' }}
         with:
           path: formatted-trivy-result.md
       
       - name: Check if vulnerabilities exist
+        if: ${{ steps.trivy.outcome == 'failure' }}
         run: |
-          if [ -s trivy-result.txt ]; then
-            echo -e "Vulnerabilities found in the image. Failing the build."
-            exit 1
-          fi
-
+          echo -e "Vulnerabilities found in the image. Failing the build."
+          exit 1
+          
       - name: Publish minio image
         working-directory: images/minio
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
